version: "3.3"

services:
  master: 
    image: ozlevka/shield-elk:latest
    environment:
      - "ELASTIC_CMD_OPTIONS=--E network.host=0"
      - "LOGSTASH_LOG_LEVEL=info"
    ports:
      - 9200:9200
      - 5601:5601
    networks:
      - default
    links:
      - consul

  consul:
    image: consul:1.0.1
    command: agent -dev -ui -client=0.0.0.0
    ports:
      - 8500:8500
    networks:
         - default
    environment:
        - "CONSUL_BIND_INTERFACE=eth0"
networks:
  default: